<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapToOED_CanAccA_var2_create_rec">
		<xsl:param name="var1_current"/>
		<rec>
			<xsl:copy-of select="$var1_current/@node()"/>
			<xsl:copy-of select="$var1_current/node()"/>
		</rec>
	</xsl:template>
	<xsl:template name="agt:MapToOED_CanAccA_var4_resultof_map">
		<xsl:param name="var3_current"/>
		<xsl:for-each select="$var3_current/rec">
			<xsl:call-template name="agt:MapToOED_CanAccA_var2_create_rec">
				<xsl:with-param name="var1_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<root>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">C:/Users/Administrator/Desktop/git/ReinsuranceTestTool/Transformations/ValidationFiles/OED_CanAccA.xsd</xsl:attribute>
			<xsl:for-each select="root">
				<xsl:call-template name="agt:MapToOED_CanAccA_var4_resultof_map">
					<xsl:with-param name="var3_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</root>
	</xsl:template>
</xsl:stylesheet>
