FROM ubuntu:16.04

RUN apt update && apt upgrade -y && apt install -y \
    apache2 \
    apache2-utils \
    libapache2-mod-wsgi \
    python-pip \
    python-dev \
    build-essential \
    python-flask \
    libgeos-dev \
    unixodbc \
    unixodbc-dev

RUN mkdir /var/www/oasis && \
    mkdir /var/oasis && \
    mkdir /var/log/oasis && \
    chown www-data:www-data /var/log/oasis && \
    chmod 744 /var/log/oasis && \
    touch /var/log/oasis/keys_server.log && \
    chown www-data:www-data /var/log/oasis/keys_server.log && \
    chmod 644 /var/log/oasis/keys_server.log

COPY ./keys_server_config/apache2.conf /etc/apache2/
COPY ./keys_server_config/oasis.conf /etc/apache2/sites-available/
COPY ./keys_server_config/oasis.wsgi /var/www/oasis/

RUN mkdir /var/www/oasis/oasis_keys_server
COPY ./src/oasis_keys_server/ /var/www/oasis/oasis_keys_server/
RUN rm -fr /var/www/oasis/oasis_keys_server/docs && \
    rm -fr /var/www/oasis/oasis_keys_server/venv

RUN mkdir /var/www/oasis/keys_server
COPY ./src/keys_server/__init__.py.base /var/www/oasis/keys_server/__init__.py
RUN echo "\nfrom .PiWind import *" >> /var/www/oasis/keys_server/__init__.py
COPY ./src/keys_server/utils.py /var/www/oasis/keys_server/
COPY ./src/keys_server/requirements.txt /var/www/oasis/keys_server/
RUN mkdir /var/www/oasis/keys_server/PiWind
COPY ./src/keys_server/PiWind/ /var/www/oasis/keys_server/PiWind/
COPY ./src/keys_server/PiWind/KeysServer.ini /var/www/oasis_keys_server/

RUN mkdir /var/oasis/keys_data && \
    chown www-data:www-data /var/oasis/keys_data && \
    chmod -R 744 /var/oasis/keys_data
COPY ./keys_data/PiWind/ /var/oasis/keys_data/

COPY ./src/oasis_keys_server/startup.sh  /usr/local/bin/
RUN chmod +x /usr/local/bin/startup.sh

RUN pip install -r /var/www/oasis/oasis_keys_server/requirements.txt && \
    pip install -r /var/www/oasis/keys_server/requirements.txt && \
    pip install -r /var/www/oasis/keys_server/PiWind/requirements.txt

RUN a2dissite 000-default && \
    a2ensite oasis.conf
EXPOSE 5000

ENTRYPOINT startup.sh; tail -f /var/log/oasis/keys_server.log
