FROM coreoasis/model_execution_worker:OASIS_0_0_0_167

COPY ./src/model_execution_worker/OasisLMF ./model_execution_worker/OasisLMF
COPY ./model_data/PiWind /var/oasis/model_data/OasisLMF/PiWind
RUN touch /var/log/oasis/celery_worker.log
RUN chmod 666 /var/log/oasis/celery_worker.log

ENTRYPOINT
# Define entry points here
