FROM coreoasis/model_execution_worker:OASIS_0_0_0_228

USER worker
WORKDIR /home/worker

COPY ./src/model_execution_worker/OasisLMF ./model_execution_worker/OasisLMF
COPY ./model_data/PiWind /var/oasis/model_data/OasisLMF/PiWind
RUN touch /var/log/oasis/worker.log
RUN touch /var/log/oasis/celery_worker.log
RUN chmod 666 /var/log/oasis/celery_worker.log

ENTRYPOINT \
	sed -i -e "s/%CELERY_QUEUE%/$MODEL_SUPPLIER_ID-$MODEL_VERSION_ID/" startup.sh && \
	sed -i -e "s/%RABBIT_PORT%/$RABBIT_PORT/" /home/worker/common/CeleryConfig.py && \
	./utils/wait-for-it.sh "rabbit:$RABBIT_PORT" -t 60 && \
	sed -i -e "s/%MYSQL_PORT%/$MYSQL_PORT/" /home/worker/common/CeleryConfig.py && \
	./utils/wait-for-it.sh "mysql:$MYSQL_PORT" -t 60 && \
	./startup.sh && \
	tail -f /var/log/oasis/worker.log
