FROM coreoasis/model_execution_worker:OASIS_0_0_214_0

COPY ./src/model_execution_worker/OasisLMF  ./model_execution_worker/OasisLMF
COPY ./model_data/PiWind /var/oasis/model_data/OasisLMF/PiWind
RUN touch /var/log/oasis/celery_worker.log
RUN chmod a+w /var/log/oasis/celery_worker.log

ENTRYPOINT \
	sed -i -e "s/%RABBIT_PORT%/$RABBIT_PORT/" /home/worker/common/CeleryConfig.py && \
	sed -i -e "s/%MYSQL_PORT%/$MYSQL_PORT/" /home/worker/common/CeleryConfig.py && \
	./utils/wait-for-it.sh "rabbit:$RABBIT_PORT" && \
	./utils/wait-for-it.sh "mysql:$MYSQL_PORT" && \
    ./startup.sh && \
	tail -f /var/log/oasis/celery_worker.log