version: '3'
volumes:
  server-db-OasisData:
  celery-db-OasisData:
  filestore-OasisData:
services:
  server:
   restart: always
   image: coreoasis/api_server:$OASIS_PLATFORM_VERSION
   ports:
     - 8000:8000
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_ADMIN_USER=admin
     - OASIS_ADMIN_PASS=password
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
     - STARTUP_RUN_MIGRATIONS=true
     - OASIS_DEBUG=True
   volumes:
     - filestore-OasisData:/shared-fs:rw
  worker-monitor:
   restart: always
   image: coreoasis/api_server:$OASIS_PLATFORM_VERSION
   command: [wait-for-server, 'server:8000', celery, -A, src.server.oasisapi, worker, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - rabbit
   environment:
     - OASIS_DEBUG=1
     - OASIS_RABBIT_HOST=rabbit
     - OASIS_RABBIT_PORT=5672
     - OASIS_RABBIT_USER=rabbit
     - OASIS_RABBIT_PASS=rabbit
     - OASIS_SERVER_DB_HOST=server-db
     - OASIS_SERVER_DB_PASS=oasis
     - OASIS_SERVER_DB_USER=oasis
     - OASIS_SERVER_DB_NAME=oasis
     - OASIS_SERVER_DB_PORT=3306
     - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
     - OASIS_CELERY_DB_HOST=celery-db
     - OASIS_CELERY_DB_PASS=password
     - OASIS_CELERY_DB_USER=celery
     - OASIS_CELERY_DB_NAME=celery
     - OASIS_CELERY_DB_PORT=3306
   volumes:
     - filestore-OasisData:/shared-fs:rw
  server-db:
    restart: always
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=oasis
      - MYSQL_PASSWORD=oasis
      - MYSQL_DATABASE=oasis
    volumes:
      - /home/ubuntu/data/db-data/server:/var/lib/mysql:rw
  celery-db:
    restart: always
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=celery
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=celery
    volumes:
      - /home/ubuntu/data/db-data/celery:/var/lib/mysql:rw
  rabbit:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
  piwind_worker:
    image: piwind_worker:$OASIS_WORKER_VERSION 
    restart: unless-stopped
    depends_on:
      - celery-db
      - rabbit
    environment:
      - FARM_LOG_DIR=/tmp
      - OASIS_MODEL_SUPPLIER_ID=OasisLMF
      - OASIS_MODEL_ID=PiWind
      - OASIS_MODEL_VERSION_ID=1
      - OASIS_RABBIT_HOST=rabbit
      - OASIS_RABBIT_PORT=5672
      - OASIS_RABBIT_USER=rabbit
      - OASIS_RABBIT_PASS=rabbit
      - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
      - OASIS_CELERY_DB_HOST=celery-db
      - OASIS_CELERY_DB_PASS=password
      - OASIS_CELERY_DB_USER=celery
      - OASIS_CELERY_DB_NAME=celery
      - OASIS_CELERY_DB_PORT=3306
      # The ulimit command that this adds to the bash script causes segfaults
      # when importing modules in Python 3.6. I don't understand why - Daniel Evans
      - OASIS_KTOOLS_MEMORY_LIMIT=False
      - OASIS_MODEL_SETTINGS_FILE=/var/oasis/meta-data/model_settings.json
    volumes:
      - /home/ubuntu/data/keys_data:/var/oasis/keys_data:rw
      - /home/ubuntu/data/model_data:/var/oasis/model_data:rw
      - filestore-OasisData:/shared-fs:rw
  shiny_proxy:
    restart: always
    container_name: oasisui_proxy
    image: coreoasis/oasisui_proxy:$OASIS_UI_VERSION
    ports:
     - 8080:8080
    environment:
     #- API_IP=<FOR_REMOTE_IPs>
     - UI_DOCKER_IMAGE=coreoasis/oasisui_app:$OASIS_UI_VERSION
     - API_PORT=8000
     - API_VERSION=v1
     - API_SHARE_FILEPATH=./downloads
     - OASIS_ENVIRONMENT=oasis_localhost
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - shiny-net
networks:
  shiny-net:
    external: true
