version: '3'
services:
  piwind_worker:
    image: piwind_worker:$OASIS_WORKER_VERSION 
    restart: unless-stopped
    depends_on:
      - celery-db
      - rabbit
    environment:
      - FARM_LOG_DIR=/tmp
      - OASIS_MODEL_SUPPLIER_ID=OasisLMF
      - OASIS_MODEL_ID=PiWind
      - OASIS_MODEL_VERSION_ID=1
      - OASIS_RABBIT_HOST=rabbit
      - OASIS_RABBIT_PORT=5672
      - OASIS_RABBIT_USER=rabbit
      - OASIS_RABBIT_PASS=rabbit
      - OASIS_CELERY_DB_ENGINE=db+mysql+pymysql
      - OASIS_CELERY_DB_HOST=celery-db
      - OASIS_CELERY_DB_PASS=password
      - OASIS_CELERY_DB_USER=celery
      - OASIS_CELERY_DB_NAME=celery
      - OASIS_CELERY_DB_PORT=3306
      - OASIS_KTOOLS_MEMORY_LIMIT=False
      - OASIS_MODEL_SETTINGS_FILE=/var/oasis/meta-data/model_settings.json
    volumes:
      - /home/ubuntu/data/keys_data:/var/oasis/keys_data:rw
      - /home/ubuntu/data/model_data:/var/oasis/model_data:rw
      - filestore-OasisData:/shared-fs:rw

