ARG worker_ver=latest
ARG worker_img=coreoasis/model_worker
FROM $worker_img:$worker_ver

WORKDIR /home/worker

COPY ./docker/oasislmf_deploy.json /home/worker/model/oasislmf.json
COPY ./meta-data/model_settings.json /home/worker/model/meta-data/model_settings.json

ENTRYPOINT ./startup.sh
