FROM coreoasis/model_keys_server2:latest

COPY ./src/keys_server/PiWind/KeysServer.ini /var/www/oasis_keys_server/

RUN mkdir /var/oasis/keys_data && \
    chown www-data:www-data /var/oasis/keys_data && \
    chmod -R 744 /var/oasis/keys_data
COPY ./keys_data/PiWind/ /var/oasis/keys_data/

ENTRYPOINT ["/bin/sh", "-c", "startup.sh"]
