name: build

on:
  push

env:
  # model_git_url: OasisLMF/OasisPiWind.git
  BUILD_REPO: OasisLMF/build
  BUILD_BRANCH: master
  BUILD_WORKER: ${{ false }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone PiWind repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
          ref: ${{ env.BUILD_BRANCH }}

      - name: build worker
        if: ${{ env.BUILD_WORKER }}
        run: echo ciao
      - name: build worker
        if: ! ${{ env.BUILD_WORKER }}
        run: echo ciao     

