name: build

on:
  push

env:
  # model_git_url: OasisLMF/OasisPiWind.git
  BUILD_REPO: OasisLMF/build
  BUILD_BRANCH: master
  BUILD_WORKER: false
  LAST_RELEASE_TAG: ''
  TAG_OASIS: 'latest'
  TAG_RELEASE: ${{ github.ref_name }}-${{ github.run_number }}  # similar (split by / is missing)
  BUILD_WORKSPACE: oasis_build
  MODEL_WORKSPACE: piwind_workspace

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone PiWind repository
        uses: actions/checkout@v3
        with:
          submodules: true
          path: ${{ env.MODEL_WORKSPACE }}
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
          ref: ${{ env.BUILD_BRANCH }}
          path: ${{ env.BUILD_WORKSPACE }}
      - name: set default vars
        run: |
          echo "TAG_OASIS=${TAG_OASIS}" >> $GITHUB_ENV 
          echo "TAG_RELEASE=${TAG_RELEASE}" >> $GITHUB_ENV 
          echo "TAG_RUN_PLATFORM=${TAG_OASIS}" >> $GITHUB_ENV 
          echo "TAG_RUN_WORKER=${TAG_OASIS}" >> $GITHUB_ENV 
          echo "PIPELINE=${BUILD_WORKSPACE}/buildscript/pipeline.sh" >> $GITHUB_ENV 

      - name: build worker
        # see open issue on if statements 
        # https://github.com/actions/runner/issues/1173
        if: env.BUILD_WORKER == 'true'
        run: echo "build worker TBD"
      - name: build worker2
        id: build-worker2
        if: env.BUILD_WORKER == 'false' && env.TAG_OASIS == 'latest'
        run: |
          echo ${{ env.BUILD_WORKER }} 
          LAST_RELEASE_TAG=$(curl https://api.github.com/repos/OasisLMF/OasisPlatform/releases | jq -r '( first ) | .name')
          echo "LAST_RELEASE_TAG=${LAST_RELEASE_TAG}" >> $GITHUB_ENV 
          echo "TAG_RUN_WORKER=${LAST_RELEASE_TAG}" >> $GITHUB_ENV 
          echo "TAG_RUN_PLATFORM=${LAST_RELEASE_TAG}" >> $GITHUB_ENV 
      - name: list
        run: |
          ls .
      - name: shell env
        run: $PIPELINE print_model_vars
          
