name: build

on:
  push

env:
  # model_git_url: OasisLMF/OasisPiWind.git
  BUILD_REPO: OasisLMF/build
  BUILD_BRANCH: master
  BUILD_WORKER: false
  LAST_RELEASE_TAG: ''
  TAG_OASIS: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone PiWind repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
          ref: ${{ env.BUILD_BRANCH }}

      - name: build worker
        # see open issue on if statements 
        # https://github.com/actions/runner/issues/1173
        if: env.BUILD_WORKER == 'true'
        run: echo "build worker TBD"
      - name: build worker
        if: env.BUILD_WORKER == 'false' && env.TAG_OASIS == 'latest'
        run: |
          echo ${{ env.BUILD_WORKER }} 
          echo "LAST_RELEASE_TAG=$(curl https://api.github.com/repos/OasisLMF/OasisPlatform/releases | jq -r '( first ) | .name')" >> $GITHUB_ENV  
          echo "TAG_RUN_WORKER=$(echo ${LAST_RELEASE_TAG})" >> $GITHUB_ENV  
          echo "TAG_RUN_PLATFORM=$(echo ${LAST_RELEASE_TAG})" >> $GITHUB_ENV  
      - name: print vars
        run: echo ${{ env.LAST_RELEASE_TAG }}
