name: build

on:
  push

env:
  # model_git_url: OasisLMF/OasisPiWind.git
  BUILD_REPO: OasisLMF/build


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone PiWind repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: clone build repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.BUILD_REPO }}
             




