
name: check_results

on:
  push:
  workflow_dispatch:
    inputs:
      build_branch:
        description: 'Branch of build script repo - https://github.com/OasisLMF/build'
        required: true
        default: master
      platform_version:
        description: 'OasisPlatform Version'
        required: true
        default: latest
      mdk_branch:
        description: 'Oasislmf Branch to test'
        required: true
        default: develop
      build_worker:
        description: 'Build piwind worker from branch or package'
        required: true
        default: true


jobs:
  check_results:
    runs-on: ubuntu-latest
    env:
      SERVER_IMG: 'coreoasis/api_server'
      SERVER_TAG: '1.26.4'
      WORKER_IMG: 'coreoasis/model_worker'
      WORKER_TAG: '1.26.4'
      DEBUG: 0

    steps:
    - name: clone PiWind repository
      uses: actions/checkout@v3
      with:
        repository: OasisLMF/OasisPiWind
        #fetch-depth: 1
        #ref: ${{ env.PIWIND_BRANCH }}
        #path: ${{ env.MODEL_WORKSPACE }}


    - name: Setup Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install test deps  
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile tests/requirements.in -o tests/requirements.txt
        pip install -r tests/requirements.txt

    - name: Run Checks 
      run: pytest -v
