name: PiWind Testing 


on: push


env:
  oasislmf_branch: 'develop'
  piwind_branch: ${{  github.ref_name }}
  piwind_img_repo: 'coreoasis/github-actions'
  piwind_img_tag: 'piwind_worker-${{ github.sha }}'



# run piwind build 
jobs:
  # https://github.com/actions/runner/issues/480#issuecomment-1055373623
  # Workaround because 'env' is not in context
  params:
    name: Update params based on current branch
    runs-on: ubuntu-latest
    outputs:
      # build params  
      piwind_image: ${{ steps.export_param.outputs.piwind_image }}
      oasislmf_branch: ${{ steps.export_param.outputs.oasislmf_branch }}

      # test params 
      worker_image: ${{ steps.export_param.outputs.worker_image }}
      worker_tag: ${{ steps.export_param.outputs.worker_tag }}
    
    step: 
    - name: Update params 
      run: | 
        [[ "${{ env.piwind_branch }}" = "master" ]] && echo "oasislmf_branch=master" >> $GITHUB_ENV

    - id: export_param
      name: Output params
      run: |
        echo "piwind_image=${{ env.piwind_img_repo }}:${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT       
        echo "oasislmf_branch=${{ env.oasislmf_branch }}" >> $GITHUB_OUTPUT       
        echo "worker_image=${{ env.piwind_img_repo }}" >> $GITHUB_OUTPUT       
        echo "worker_tag=${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT       

  build:
    uses: ./.github/workflows/build.yml
    needs: [params]
    with:
      docker_push: 'true'
      from_image: 'coreoasis/model_worker:latest'
      piwind_branch: ${{ github.ref_name }}
      piwind_image: ${{ needs.params.outputs.piwind_image }}
      oasislmf_branch: ${{ needs.params.outputs.oasislmf_branch }}

  test:
    name: PiWind Integration ()
    uses: ./.github/workflows/integration.yml
    needs: [params, build]
    with:
    inputs:
      pwind_branch: ${{ github.ref_name }}
      worker_image: ${{ needs.build.outputs.worker_image }}
      worker_tag: ${{ needs.params.outputs.worker_tag }}
      server_tag: "latest"
      debug_mode: 0
