name: PiWind Testing


on:
  push:
  workflow_dispatch:
    inputs:
      oasislmf_branch:
        description: "Branch from oasislmf to test piwind with [git ref]"
        required: True
        default: 'develop'
        type: string

  workflow_call:
    inputs:
      piwind_branch:
        description: "PiWind branch to test results [git ref]"
        required: True
        type: string

      oasislmf_branch:
        description: "Branch from oasislmf to test piwind with [git ref]"
        required: false
        default: 'develop'
        type: string

      oasislmf_package:
        description: "Oasislmf package build to test [pkg_filename]"
        required: false
        default: ''
        type: string

      platform_version:
        description: "Platform Version tag [semvar]"
        required: false
        default: ''
        type: string

env:
  oasislmf_branch: 'develop'
  oasislmf_package: ''
  piwind_branch: ${{ github.ref_name }}
  piwind_img_repo: 'coreoasis/github-actions'
  piwind_img_tag: 'piwind_worker-${{ github.sha }}'
  platform_tag: 'latest'

jobs:
  # https://github.com/actions/runner/issues/480#issuecomment-1055373623
  # Workaround because 'env' is not in context
  params:
    name: Update params
    runs-on: ubuntu-latest
    outputs:
      piwind_branch: ${{ steps.export_param.outputs.piwind_branch }}
      piwind_image: ${{ steps.export_param.outputs.piwind_image }}
      oasislmf_branch: ${{ steps.export_param.outputs.oasislmf_branch }}
      oasislmf_package: ${{ steps.export_param.outputs.oasislmf_package }}
      from_image: ${{ steps.export_param.outputs.from_image }}
      worker_image: ${{ steps.export_param.outputs.worker_image }}
      worker_tag: ${{ steps.export_param.outputs.worker_tag }}
      server_tag: ${{ steps.export_param.outputs.server_tag }}

    steps:
    - name: Set Inputs
      run: |
        [[ -z "${{ inputs.piwind_branch }}" ]] || echo "piwind_branch=${{ inputs.piwind_branch }}" >> $GITHUB_ENV
        [[ -z "${{ inputs.oasislmf_branch }}" ]] || echo "oasislmf_branch=${{ inputs.oasislmf_branch }}" >> $GITHUB_ENV
        [[ -z "${{ inputs.oasislmf_package }}" ]] || echo "oasislmf_package=${{ inputs.oasislmf_package }}" >> $GITHUB_ENV
        [[ -z "${{ inputs.platform_version }}" ]] || echo "platform_tag=${{ inputs.platform_version }}" >> $GITHUB_ENV

    - name: Update params
      run: |
        # Match PiWind branch to Oasislmf
        if [[ "${{ env.piwind_branch }}" = "master" ]]; then
          echo "oasislmf_branch=master" >> $GITHUB_ENV
        fi
        if [[ "${{ env.piwind_branch }}" = backports* ]]; then
          echo "oasislmf_branch=${{ env.piwind_branch }}" >> $GITHUB_ENV
        fi
        # Match Oasislmf branch to PiWind
        if [[ "${{ env.oasislmf_branch }}" = "master" ]]; then
          echo "piwind_branch=master" >> $GITHUB_ENV
        fi
        if [[ "${{ env.oasislmf_branch }}" = backports* ]]; then
          echo "piwind_branch=${{ env.oasislmf_branch }}" >> $GITHUB_ENV
        fi
        # If oasislmf package is given remove branch install option
        if [[ -n "${{ inputs.oasislmf_package }}" ]]; then
            echo "oasislmf_package=" >> $GITHUB_ENV
        fi

    - id: export_param
      name: Output params
      run: |
        echo "piwind_branch=${{ env.piwind_branch }}" >> $GITHUB_OUTPUT
        echo "piwind_image=${{ env.piwind_img_repo }}:${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT
        echo "oasislmf_branch=${{ env.oasislmf_branch }}" >> $GITHUB_OUTPUT
        echo "oasislmf_package=${{ env.oasislmf_package }}" >> $GITHUB_OUTPUT
        echo "from_image=coreoasis/model_worker:${{ env.platform_tag }}" >> $GITHUB_OUTPUT
        echo "worker_image=${{ env.piwind_img_repo }}" >> $GITHUB_OUTPUT
        echo "worker_tag=${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT
        echo "server_tag=${{ env.platform_tag }}" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [params]
    with:
      docker_push: 'true'
      from_image: ${{ needs.params.outputs.from_image }}
      piwind_branch: ${{ needs.params.outputs.piwind_branch }}
      oasislmf_package: ${{ needs.params.outputs.oasislmf_package }}
      oasislmf_branch: ${{ needs.params.outputs.oasislmf_branch }}

  test:
    name: PiWind Integration
    uses: ./.github/workflows/integration.yml
    secrets: inherit
    needs: [params, build]
    with:
      pwind_branch: ${{ needs.params.outputs.piwind_branch }}
      worker_image: ${{ needs.params.outputs.worker_image }}
      worker_tag: ${{ needs.params.outputs.worker_tag }}
      server_tag: ${{ needs.params.outputs.server_tag }}
      debug_mode: 0
