name: PiWind Testing 


on: 
  push:
  workflow_dispatch:
    inputs:
      oasislmf_branch: 
        description: "Branch from oasislmf to test piwind with [git ref]"
        required: True
        default: 'develop'
        type: string
    
env:
  oasislmf_branch: 'develop'
  piwind_branch: ${{  github.ref_name }}
  piwind_img_repo: 'coreoasis/github-actions'
  piwind_img_tag: 'piwind_worker-${{ github.sha }}'

jobs:
  # https://github.com/actions/runner/issues/480#issuecomment-1055373623
  # Workaround because 'env' is not in context
  params:
    name: Update params
    runs-on: ubuntu-latest
    outputs:
      # build params  
      piwind_image: ${{ steps.export_param.outputs.piwind_image }}
      oasislmf_branch: ${{ steps.export_param.outputs.oasislmf_branch }}
      # test params 
      worker_image: ${{ steps.export_param.outputs.worker_image }}
      worker_tag: ${{ steps.export_param.outputs.worker_tag }}
    
    steps: 
    - name: Update params 
      run: | 
        if [[ "${{ env.piwind_branch }}" = "master" ]]; then 
          echo "oasislmf_branch=master" >> $GITHUB_ENV
        fi   
        if [[ "${{ env.piwind_branch }}" = backports* ]]; then
          echo "oasislmf_branch=${{ env.piwind_branch }}" >> $GITHUB_ENV
        fi 

    - name: Set oasislmf branch
      if: github.event_name == 'workflow_dispatch'
      run: echo "oasislmf_branch=${{ inputs.oasislmf_branch }}" >> $GITHUB_OUTPUT

    - id: export_param
      name: Output params
      run: |
        echo "piwind_image=${{ env.piwind_img_repo }}:${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT       
        echo "oasislmf_branch=${{ env.oasislmf_branch }}" >> $GITHUB_OUTPUT       
        echo "worker_image=${{ env.piwind_img_repo }}" >> $GITHUB_OUTPUT       
        echo "worker_tag=${{ env.piwind_img_tag }}" >> $GITHUB_OUTPUT       

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [params]
    with:
      docker_push: 'true'
      from_image: 'coreoasis/model_worker:latest'
      piwind_branch: ${{ github.ref_name }}
      piwind_image: ${{ needs.params.outputs.piwind_image }}
      oasislmf_branch: ${{ needs.params.outputs.oasislmf_branch }}

  test:
    name: PiWind Integration
    uses: ./.github/workflows/integration.yml
    secrets: inherit
    needs: [params, build]
    with:
      pwind_branch: ${{ github.ref_name }}
      worker_image: ${{ needs.params.outputs.worker_image }}
      worker_tag: ${{ needs.params.outputs.worker_tag }}
      server_tag: "latest"
      debug_mode: 0
